#!/usr/bin/env python3
"""
migrate_schema.py — One-time schema migration for Pelimotion
==============================================================
Reads the current site-content.json and upgrades every Client and MediaItem
to the v3 unified schema. All existing data is preserved. Missing fields
are added with safe defaults.

Run once:  python3 migrate_schema.py
"""
import json
import re
import time
import os

INPUT_FILE  = "site-content.json"
OUTPUT_FILE = "site-content.json"  # in-place

SCHEMA_VERSION = "3.0"

# ─── HELPERS ────────────────────────────────────────────────────────────────

def make_slug(name: str) -> str:
    """'FUNKY ROOM' → 'funky-room'"""
    s = name.lower().strip()
    s = re.sub(r'[^a-z0-9\s-]', '', s)
    s = re.sub(r'[\s_]+', '-', s)
    s = re.sub(r'-+', '-', s)
    return s.strip('-')

def now_iso() -> str:
    return time.strftime('%Y-%m-%dT%H:%M:%SZ', time.gmtime())

# ─── CLIENT MIGRATION ───────────────────────────────────────────────────────

def migrate_client(name: str, client: dict, order_index: int) -> dict:
    """
    Takes an existing client dict and returns the v3 version.
    Fields that already exist are kept as-is.
    New required fields get safe defaults.
    """
    # --- Auto-generated fields (owned by sync_bunny, always refreshed) ---
    # These are NOT touched here; they come from Bunny.
    # We just ensure the 'media' wrapper has the right shape.
    media = client.get("media", {})
    if "root" not in media:       media["root"] = []
    if "categories" not in media: media["categories"] = {}
    if "total" not in media:      media["total"] = 0

    # Migrate each root media item
    media["root"] = [migrate_media_item(m, i) for i, m in enumerate(media["root"])]

    # Migrate each category's media items
    for cat_name, items in media.get("categories", {}).items():
        media["categories"][cat_name] = [migrate_media_item(m, i) for i, m in enumerate(items)]

    # --- Editorial fields (owned by admin, never overwritten by sync) ---
    return {
        # ── Identity ──
        "slug":         client.get("slug")        or make_slug(name),
        "displayName":  client.get("displayName") or name,  # editable display name

        # ── Content (editorial) ──
        "description":    client.get("description")    or "",
        "description_pt": client.get("description_pt") or "",
        "tags":           client.get("tags")           or [],   # e.g. ["motion branding", "social media"]
        "services":       client.get("services")       or [],   # e.g. ["After Effects", "Premiere"]
        "since":          client.get("since")          or "",   # e.g. "2023"
        "externalUrl":    client.get("externalUrl")    or "",

        # ── Presentation ──
        "status":         client.get("status")         or "public",  # public | private | draft
        "order":          client.get("order", order_index),           # explicit ordering
        "coverImage":     client.get("coverImage")     or "",
        "mosaicAssets":   client.get("mosaicAssets")   or [],  # list of 3 asset URLs chosen in admin

        # ── SEO ──
        "seo": {
            "title":       client.get("seo", {}).get("title")       or f"{name} — Pelimotion",
            "description": client.get("seo", {}).get("description") or "",
            "ogImage":     client.get("seo", {}).get("ogImage")     or client.get("coverImage", ""),
        },

        # ── Media (auto-generated by sync_bunny) ──
        "media": media,

        # ── Timestamps ──
        "createdAt":  client.get("createdAt")  or now_iso(),
        "updatedAt":  client.get("updatedAt")  or now_iso(),
        "syncedAt":   client.get("syncedAt")   or "",  # filled by sync_bunny on each sync
    }

# ─── MEDIA ITEM MIGRATION ───────────────────────────────────────────────────

def migrate_media_item(item: dict, index: int) -> dict:
    """
    Takes an existing media item and returns the v3 version.
    Auto-generated fields (video_url, preview_url, poster_url, mosaic) are preserved.
    Editorial fields get safe defaults if missing.
    """
    # Build a stable id from the video URL if possible
    existing_id = item.get("id") or ""
    if not existing_id:
        url = item.get("video_url") or item.get("poster_url") or ""
        filename = url.split("/")[-1].rsplit(".", 1)[0]
        existing_id = make_slug(filename) if filename else f"item-{index}"

    return {
        # ── Identity ──
        "id":    existing_id,
        "order": item.get("order", index),

        # ── Auto-generated (owned by sync_bunny) ──
        "title":       item.get("title")       or "",
        "video_url":   item.get("video_url")   or "",
        "preview_url": item.get("preview_url") or "",
        "poster_url":  item.get("poster_url")  or "",
        "mosaic":      item.get("mosaic")      or [],
        "format":      item.get("format")      or "default",
        "aspect":      item.get("aspect")      or "16/9",

        # ── Editorial (owned by admin) ──
        "title_pt":       item.get("title_pt")       or "",
        "description":    item.get("description")    or "",
        "description_pt": item.get("description_pt") or "",
        "tags":           item.get("tags")           or [],
        "status":         item.get("status")         or "public",  # public | private | draft

        # ── Timestamps ──
        "updatedAt": item.get("updatedAt") or now_iso(),
    }

# ─── MAIN ────────────────────────────────────────────────────────────────────

def main():
    print(f"\n📦 migrate_schema.py — Pelimotion Schema v{SCHEMA_VERSION}")
    print("=" * 56)

    if not os.path.exists(INPUT_FILE):
        print(f"❌ {INPUT_FILE} not found. Aborting.")
        return

    with open(INPUT_FILE, "r", encoding="utf-8") as f:
        data = json.load(f)

    # Grab current clientOrder to preserve ordering
    client_order = data.get("clientOrder", [])
    clients_raw  = data.get("clients", {})

    # Build ordered list: clientOrder first, then any not in order
    ordered_names = list(dict.fromkeys(
        client_order + [k for k in clients_raw if k not in client_order]
    ))

    # Migrate each client
    migrated_clients = {}
    for idx, name in enumerate(ordered_names):
        if name not in clients_raw:
            print(f"  ⚠️  '{name}' in clientOrder but not in clients — skipping")
            continue
        migrated_clients[name] = migrate_client(name, clients_raw[name], idx)
        print(f"  ✅ {name}")

    # Patch top-level metadata
    data["_version"]        = SCHEMA_VERSION
    data["_schemaNote"]     = (
        "v3 unified schema. Auto-generated fields (video_url, preview_url, poster_url, "
        "mosaic, syncedAt) are owned by sync_bunny.py and overwritten on each sync. "
        "Editorial fields (description, slug, tags, seo, order, status) are owned by "
        "admin and never overwritten by sync."
    )
    data["clients"]         = migrated_clients
    data["lastMigration"]   = now_iso()

    with open(OUTPUT_FILE, "w", encoding="utf-8") as f:
        json.dump(data, f, indent=2, ensure_ascii=False)

    print(f"\n✅ Migration complete — {len(migrated_clients)} clients updated.")
    print(f"   Written to: {OUTPUT_FILE}")
    print(f"\n⚠️  Next step: also run sync_bunny.py to refresh 'syncedAt' timestamps.\n")

if __name__ == "__main__":
    main()
